# Generated by Django 3.2.7 on 2021-10-27 18:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracking',
            new_name='Priority_tracking',
        ),
    ]
