# Generated by Django 3.2.7 on 2021-10-28 07:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_rename_priority_tracking_prioritytracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioritytracking',
            name='priority',
            field=models.CharField(max_length=26, unique=True, validators=[django.core.validators.MinLengthValidator(26)]),
        ),
    ]
