# Generated by Django 3.2.7 on 2022-07-28 20:18

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_labeldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeldata',
            name='senderData',
            field=jsonfield.fields.JSONField(default='jjj'),
            preserve_default=False,
        ),
    ]
