# Generated by Django 3.2.7 on 2022-08-14 21:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_alter_labeldata_senderdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mylist', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=None), size=None)),
            ],
        ),
    ]
