# Generated by Django 3.2.7 on 2022-09-08 16:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0007_alter_labeldata_senderdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstClassTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_class', models.CharField(max_length=26, unique=True, validators=[django.core.validators.MinLengthValidator(26)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
